id = "2"
correct = "B"

choices = [
	{ value= "A", description = "Option A"},
	{ value = "B", description = "Option B (this is correct)"},
	{ value = "C", description = "Option C"}
]

description = """
Pick
A\
"""

codelanguage = "js"