id = "2"
correct = "A"

description = """
Pick
A
(example without code)\
"""

choices = [
	{ value= "A", description = "Option A (this is correct)"},
	{ value = "B", description = "Option B"},
	{ value = "C", description = "Option C"}
]
